// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYYxCFUlOJTr77so8wvCFgZ1sze3UCl2U',
    appId: '1:617332712958:web:6b7e4048cb930a67ec8caf',
    messagingSenderId: '617332712958',
    projectId: 'lepsyhub',
    authDomain: 'lepsyhub.firebaseapp.com',
    storageBucket: 'lepsyhub.appspot.com',
    measurementId: 'G-5W0P682GRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZBpCAHAeM0l4Dz33fzia4vPhrVe4KlLY',
    appId: '1:617332712958:android:c2159afa695e14ccec8caf',
    messagingSenderId: '617332712958',
    projectId: 'lepsyhub',
    storageBucket: 'lepsyhub.appspot.com',
  );
}
